# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  host: localhost
  username: postgres
  database: autotunes-dev

test:
  adapter: postgresql
  host: localhost
  username: postgres
  database: autotunes-test

